//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_VERIS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class especialidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public especialidades()
        {
            this.medicos = new HashSet<medicos>();
        }
    
        public int IdEspecialidad { get; set; }
        public string Descripcion { get; set; }
        public string Dias { get; set; }
        public System.TimeSpan Franja_HI { get; set; }
        public System.TimeSpan Franja_HF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medicos> medicos { get; set; }
    }
}
