//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_VERIS_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoVeris_MVC_BDEntities : DbContext
    {
        public ProyectoVeris_MVC_BDEntities()
            : base("name=ProyectoVeris_MVC_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<consultas> consultas { get; set; }
        public virtual DbSet<especialidades> especialidades { get; set; }
        public virtual DbSet<medicamentos> medicamentos { get; set; }
        public virtual DbSet<medicos> medicos { get; set; }
        public virtual DbSet<pacientes> pacientes { get; set; }
        public virtual DbSet<recetas> recetas { get; set; }
    }
}
